In [1]:
import pandas as pd
import sqlite3

df=pd.read_excel('.\sports.xlsx')
conn = sqlite3.connect('sport.db')
df.to_sql('sport', conn, if_exists='replace', index=False)
df

,Children (Ages 0-12),Teenagers (Ages 13-19),Young Adults (Ages 20-39),Middle-Aged Adults (Ages 40-59),Older Adults (Ages 60+)
0,Soccer/Football,Soccer/Football,Soccer/Football,Running/Jogging,Walking
1,Basketball,Basketball,Basketball,Cycling,Golf
2,Swimming,Volleyball,Running/Jogging,Golf,Swimming
3,Gymnastics,Track and Field,Tennis,Tennis,Cycling
4,Tennis,Swimming,Gym Workouts,Swimming,Tai Chi
5,"Martial Arts (such as Taekwondo, Karate)",Tennis,Yoga,Hiking,Yoga
6,Baseball/Softball,Skateboarding,Cycling,Yoga,Bowling
7,Badminton,Badminton,Badminton,Softball/Baseball,Aerobics
8,NaN,Esports/Gaming,Rock Climbing,Soccer/Football (recreational leagues),Petanque/Bocce